env:
  global:
  # Docker Repository
  - REPO=fjudith/thingsboard-demo
  # Compute docker tag
  - TAG=`if [ "${TRAVIS_BRANCH}" == "master" ]; then echo "latest"; else echo ${TRAVIS_BRANCH} ; fi`
  # Retreive commit ID
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: "OIaxEUMcNrVx5N9GFTH1qRO9YQ0DGNQaa1J/nCPDOvJvK1pptN+/Aj5/rEIRYZYmAgAsW4h2+gJ0CycwCqidYozvU/KvL3VOgm9g0KQ7yLzPZbgEi9UC+YQEnxmwwHValia6FkizU7t5aCrRj3fmyNuKFraV39Qh5B8ZBfrEDVbK6fdzQXSqRYWoZmqO7JY3oVIZSMgyVx+h6nRKz92H7boIbnVaEMMDnhBfXUyPMIaxdaNpVvXVN577c2vjKZI8NwpZf1En++gSkOMd8fffkdBR6CeRjBZBNEh5xwNljgkAF2xQfX1gRsl+A4PQkY4FviRnrf/yW8n2sCCA0CNykD7vNI6wHzGJ/BjryjCJX7DKZjeWoqEkh9v62U1oN43BT1RfDyAsJ5amqb1dQIdW12DMHNi+v3ar8/rnFrlb/S9PyLs8kG3gB6loBJWkSsBOYPNLPNxkw+x7bLxRcw+eYKjbEZTSmUvblYpFG5rlBzv6YnydW87uaLC5VjgbC8ctx1YwlC4Xi395Tu9WQMUX9+DKVarB8gWSgQEyGXn9jyO5fwK2UpOq3RAaG2h+KmMNx4Gn2ERr1MF99fzodTFPU01I0wPcbmaRwgyYgmdlPECqTLXMeDl34lZic3gjwlGp8vqUEkg6x3NeYOz+4jJOgjrUcKcxxrb/wwzNyG+OZwc="
  - secure: "RmXJRRFGhpvdUZ+cucMaQLjnmJ5Mrvc1aelupegaWGqYSBnWIHXki6D9re1FIK8yYq5qFi39L1uEsl+2ABaXap9EOsLP9w+T9oBXruEdAoGxfiVr0pn81juYa6J7D4JG4Z5I7hWEFEjclwcCnErrG2D7scPF/XAKhgIMhBp44RL2KLoWDXNHk/ZUM69NUysrnA4phl3yaGQkmAR6dza4r6lmJ4aWSp5mcncW3By0xLzQRDC3J4SNEZ7sMjftkB65hMctP9h9U+9FIvMEE8e5/Mk9pajaY+AMhic4m5Xkfz4ayEizvaQW/XG8C1NH/nQUTjcAX+weUqhzKrKxKTmgF7FM+zHpoRVeB1+4qERpTGRDg40o0qlnNsYVt8lOjiYUhx6HdAJ6Ph+UmOi0a9z3W/M+UHUE3Rq6hKSzwKLczU6zMmooGmaC3ZebPU+3WyZDhEEU0FY0wsvfVtECdu/T46Tv14QADrM1e9H+eRjyANBWZoN4TTxaKBChgBUaw06MmdNFL0nyZVA4YvfTYjEJuB3Eq/asE59RB+vluXSQBNh8Yf8Z/hqYCnJdV7r6aQhfzWt7pbZxKCYk2yVjG3tOIYvOFG4wgZ1kvBQnK6HDturua33tgZQe3RXdk1EB78fie0acUaJxYgXSihQJ9uJ+Uxv3cVGUDNzBPMANjfZ+518="

  
sudo: required
services:
  - docker


before_install:
  # ThingsBoard Demo build
  - docker build -f Dockerfile -t $REPO:$COMMIT .

script:
  - docker images

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO