env:
  global:
  # Docker Repository
  - REPO=fjudith/thingsboard-demo
  # Compute docker tag
  - TAG=`if [ "${TRAVIS_BRANCH}" == "master" ]; then echo "latest"; else echo ${TRAVIS_BRANCH} ; fi`
  # Retreive commit ID
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: "HPeqq3FfgUDPS/P5pxhPm7s6NTrOprBmOnhRs0Y7HGZ//999RcJGbWiwbG/Zq2SUTdFDrf1RaxYqj2wP1gVgKmjzxd11jfGJF4bvpKoIKiOH6gNHutlF5roLRLo0GeqmylCr6FDRAUYo/Xw8PQcBEuYzpvlStXp0InrKgz8fvsELuxkESAc9mnArefkmEZY/2HWp3gDY/4lh2yQGFvAGVToB1FzDFcwFNmQPsCPIgl0pr141fll2QENp2LTWD2U54jcV/Kaiz9/gb9mw3cagMis8+nhLY/QYg2efGdb7JYpIB/4fIyMvq6sJQsJebOSCV1c3ZUKpE2KALpaMR1IyRSz+qR7Qwl8yQKhDp2QoBGlTkgMrET5mDlxTmaP4QdAbWjK3I1vh+2CzD5Tv1AXzVa1BnSFG7rSZtcr5FVLTEEsHzJFv7kR/+eCYAX7eD0iL3/ZQJOARqvz3tO8PzzzHNP83bP+f59pZNE/4F7Q8jL6h3Jj3gH65yKCJNDL3O35WXO2oCpA0av7wQtuIO8F3tm6paJVm3tv9KxUNj4kPGJ9PZ+mqtZBnMApRdlRPUSwxgwaWa5NUe7o1Wk6xnXsgwhPyz4Bw7dWSgZbeGAaS0PWWIMI6L0/6UPSHRAOm4ocLd9U5dzYTe3HZuVAytR6/hBpCtkFq9wD/Al45JD9GOaA="
  - secure: "RmXJRRFGhpvdUZ+cucMaQLjnmJ5Mrvc1aelupegaWGqYSBnWIHXki6D9re1FIK8yYq5qFi39L1uEsl+2ABaXap9EOsLP9w+T9oBXruEdAoGxfiVr0pn81juYa6J7D4JG4Z5I7hWEFEjclwcCnErrG2D7scPF/XAKhgIMhBp44RL2KLoWDXNHk/ZUM69NUysrnA4phl3yaGQkmAR6dza4r6lmJ4aWSp5mcncW3By0xLzQRDC3J4SNEZ7sMjftkB65hMctP9h9U+9FIvMEE8e5/Mk9pajaY+AMhic4m5Xkfz4ayEizvaQW/XG8C1NH/nQUTjcAX+weUqhzKrKxKTmgF7FM+zHpoRVeB1+4qERpTGRDg40o0qlnNsYVt8lOjiYUhx6HdAJ6Ph+UmOi0a9z3W/M+UHUE3Rq6hKSzwKLczU6zMmooGmaC3ZebPU+3WyZDhEEU0FY0wsvfVtECdu/T46Tv14QADrM1e9H+eRjyANBWZoN4TTxaKBChgBUaw06MmdNFL0nyZVA4YvfTYjEJuB3Eq/asE59RB+vluXSQBNh8Yf8Z/hqYCnJdV7r6aQhfzWt7pbZxKCYk2yVjG3tOIYvOFG4wgZ1kvBQnK6HDturua33tgZQe3RXdk1EB78fie0acUaJxYgXSihQJ9uJ+Uxv3cVGUDNzBPMANjfZ+518="

  
sudo: required
services:
  - docker


before_install:
  # ThingsBoard Demo build
  - docker build -f Dockerfile -t $REPO:$COMMIT .

script:
  - docker images

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO